name: 🚀 Update ArgoCD Image Tag in -ops Repo

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  update-ops-repo:
    runs-on: ubuntu-latest
    env:
      REPO_OPS: erickdiaz/argo-demo-app-ops
      FILE_PATH: overlays/dev/deployment_overlay.yml
      IMAGE_NAME: ghcr.io/erickdiaz/argo-demo-app

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Clone -ops repo
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://x-access-token:${{ secrets.OPS_REPO_TOKEN }}@github.com/${{ env.REPO_OPS }} ops-repo
        env:
          OPS_REPO_TOKEN: ${{ secrets.OPS_REPO_TOKEN }}

      - name: Update image tag in deployment_overlay.yml
        run: |
          cd ops-repo
          sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}|g" ${{ env.FILE_PATH }}
          git add ${{ env.FILE_PATH }}
          git commit -m "chore: update image tag to ${{ env.SHORT_SHA }}"
          git push

